### ISSUE TITLE
install doesn't work?

### ISSUE THREAD

**Issue by ghost** [basherpm/basher#45] opened 2018-10-31 04:24 UTC
Tried installing https://github.com/bashup/gitea-cli, but the only files are in ~/.basher/cellar/bin, not ~/.basher/bin, as described in the basher install files for what to set your path to.

Is it correct to have ~/.basher/cellar/bin in the path variable as well, or should it be linking packages to ~/.basher/bin?

Confused.

**Comment by juanibiapina** [comment] 2018-11-02 00:28
`~/.basher/bin` is used by the main basher binary.

`~/.basher/cellar/bin` is used by package binaries. This is added to your path by the `basher init` call.

In summary, everything is working as intended.

**Comment by toxik-io** [comment] 2018-11-02 02:20
does basher call that on its own? Am I supposed to add that in .bashrc? I don't remember that being explicitly told in the docs. Also...

```
qu@qu:~$ basher init
export BASHER_SHELL=bash
export BASHER_ROOT=/home/qu/.basher
export BASHER_PREFIX=/home/qu/.basher/cellar
export PATH="$BASHER_ROOT/cellar/bin:$PATH"
. "$BASHER_ROOT/lib/include.bash"
. "$BASHER_ROOT/completions/basher.bash"
for f in $(command ls "$BASHER_ROOT/cellar/completions/bash"); do source "$BASHER_ROOT/cellar/completions/bash/$f"; done
qu@qu:~$ eval `basher init`
bash: syntax error near unexpected token `do'
qu@qu:~$ command ls
Desktop  Documents  Downloads  failops	fo  go	Music  Pictures  Public  Templates  Videos
qu@qu:~$ command ls $BASHER_ROOT/cellar/completions/bash
ls: cannot access '/cellar/completions/bash': No such file or directory
qu@qu:~$ ls $BASHER_ROOT
Desktop  Documents  Downloads  Music  Pictures  Public  Templates  Videos
qu@qu:~$ ls $BASHER_ROOT/cellar
ls: cannot access '/cellar': No such file or directory
qu@qu:~$ eval `basher init`
bash: syntax error near unexpected token `do'
qu@qu:~$ $(basher init)
bash: export: `.': not a valid identifier
bash: export: `"$BASHER_ROOT/lib/include.bash"': not a valid identifier
bash: export: `.': not a valid identifier
bash: export: `"$BASHER_ROOT/completions/basher.bash"': not a valid identifier
bash: export: `$(command': not a valid identifier
bash: export: `"$BASHER_ROOT/cellar/completions/bash");': not a valid identifier
bash: export: `"$BASHER_ROOT/cellar/completions/bash/$f";': not a valid identifier
qu@qu:~$ 
```
basher init doesn't work xD

**Comment by toxik-io** [comment] 2018-11-03 01:43
```
basher init
+ basher init
export BASHER_SHELL=bash
export BASHER_ROOT=/home/toxik/.basher
export BASHER_PREFIX=/home/toxik/.basher/cellar
export PATH="$BASHER_ROOT/cellar/bin:$PATH"
. "$BASHER_ROOT/lib/include.bash"
. "$BASHER_ROOT/completions/basher.bash"
for f in $(command ls "$BASHER_ROOT/cellar/completions/bash"); do source "$BASHER_ROOT/cellar/completions/bash/$f"; done
```
though there's no completions in cellar/completions/bash, I can't find any syntax errors as it goes along. :/

**Comment by pawamoy** [comment] 2018-11-03 17:30
What about `eval "$(basher init - bash)"`?

**Comment by juanibiapina** [comment] 2020-11-08 15:21
Closing since there has been no reply.

**Closed by juanibiapina** 2020-11-08 15:21 UTC
